services:
  nginx:
    image: nginx:latest
    container_name: w5smtlab-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - core-api
      - room-stat-service
    networks:
      - w5smtlab_network

  core-api:
    build:
      context: ./core-api
      dockerfile: Dockerfile
    container_name: w5smtlab-core-api
    restart: always
    env_file:
      - .env
    command: php -S 0.0.0.0:9000 -t public
    volumes:
      - ./core-api:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    depends_on:
      - mysql
      - redis
    networks:
      - w5smtlab_network
    expose:
      - "9000"

  room-stat-service:
    build:
      context: ./room-stat-service
      dockerfile: Dockerfile
    container_name: w5smtlab-room-stat-service
    restart: always
    env_file:
      - .env
    command: php -S 0.0.0.0:9010 -t public
    volumes:
      - ./room-stat-service:/var/www/html
    depends_on:
      - mysql
    networks:
      - w5smtlab_network
    expose:
      - "9010"

  mysql:
    image: mysql:latest
    container_name: w5smtlab-mysql
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - w5smtlab_network

  redis:
    image: redis:latest
    container_name: w5smtlab-redis
    restart: always
    networks:
      - w5smtlab_network

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - w5smtlab_network

networks:
  w5smtlab_network:
    driver: bridge

volumes:
  mysql_data:
